TCP Chat
h31/NetworksLab2019 pull request #2
Opened 2019-10-06 19:24 UTC by stprost

Первая версия чата

2019-10-23 14:06 UTC, IgorLo commented on tcp/client/main.c
> +}
Нужно добавить перенос строки в конце файла

2019-10-23 14:09 UTC, IgorLo commented on tcp/server/main.c
> +    root = chain_init(sockfd);
Не стоит оставлять больше одной пустой строки

2019-10-23 14:10 UTC, IgorLo commented on tcp/server/main.c
> +void send_msg_to_clients(ClientChain *sender_data, char msg[], int buff_size) {
Не стоит оставлять больше одной пустой строки...

2019-10-23 14:12 UTC, IgorLo commented on tcp/client/main.c
> +    }
А если аргументов больше трёх?

2019-10-23 14:51 UTC, IgorLo commented on tcp/client/main.c
> +        buffer = (char *) malloc(buff_size);
Память только выделяется и никогда не освобождается. Возможно её стоит освобождать сразу после того, как сообщение вывелось на экран.

2019-10-24 10:12 UTC, h31 requested changes

2019-10-24 10:12 UTC, h31 commented on tcp/header.h
> +        res = read(fd, buffer + read_size, len);
Уверены, что вам всегда нужно считывать `len` байт?

2019-10-24 10:12 UTC, h31 commented on tcp/client/main.c
> +    int buff_size;
Используйте типы с фиксированным размером, например, `uint32_t`.

2019-10-24 10:12 UTC, h31 commented on tcp/header.h
> +    char name[25];
Насколько разумно для каждого никнейма всегда хранить в памяти 25 байт?

2019-10-24 10:12 UTC, h31 commented on tcp/header.h
> +    strncpy(temp->name, "null", 5);
Не забудьте потом зафиксировать в описании протокола, что такое `"null"` и как он обрабатывается

2019-10-24 10:12 UTC, h31 commented on tcp/header.h
> +void make_str(char *str) {
Имя функции слабо коррелирует с её содержимым

2019-10-24 10:12 UTC, h31 commented on tcp/server/main.c
> +        msg = (char *) malloc(25);
Почему 25, а не 26 или 30? Как можно переделать код, чтобы подобных вопросов не возникало?

2019-10-24 10:12 UTC, h31 commented on tcp/server/main.c
> +            msg = (char *) malloc(50);
Ещё одна магическая константа

2019-10-24 10:12 UTC, h31 commented on tcp/server/main.c
> +            msg = (char *) malloc(50);
Эта память где-нибудь потом освобождается?

2019-10-24 10:17 UTC, h31 requested changes

2019-10-24 10:17 UTC, h31 commented on tcp/server/main.c
> +            if (write(temp->sock, &buff_size, sizeof(int)) < 0) {
Как вы обрабатываете сценарий, когда несколько потоков пытаются записать в один сокет одновременно?

2019-10-24 10:17 UTC, h31 commented on tcp/client/main.c
> +        printf("%s\n", buffer);
1. Не обрабатывается случай, когда клиенту присылают данные во время того, как он набирает своё сообщение
2. Не забудьте потом в описании протокола указать формат сообщения

2019-11-20 22:39 UTC, h31 commented
Принято

2019-11-20 22:39 UTC, closed without merging